          - name: update nginx pkg
            apt:
              update_cache: yes
            when: update=="yes"
          - name: install nginx
            apt:
              name: nginx
              state: present 

          - name: create dir 
            file:
              path: "{{dir_name}}"
              state: directory
          - name: run ls 
            command: "ls {{dir_name}}"
            register: result
          
          - name: print debug
            debug:
              var: result.stdout

          - name: copy templet
            template:
              src: sx
              dest: sx
          
          - name: add user
            user:
              name: "{{item}}"
              state: present
            with_items:
              - osos
              - lol
              - messi